{
 "title": "Arista general overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(arista_up,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Device summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Arista Hardware Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "arista_hw_info{instance=~\"$device\"}"
    }
   ]
  },
  {
   "title": "Aggregated traffic by device",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Combined bits/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(arista_port_inOctets{device!~\"Port-Channel.*\", instance=\"$device\"}[1m])*8) ",
     "legendFormat": "Aggregated input traffic"
    },
    {
     "expr": "sum(rate(arista_port_outOctets{device!~\"Port-Channel.*\", instance=\"$device\"}[1m])*-8) ",
     "legendFormat": "Aggregated output traffic"
    }
   ]
  },
  {
   "title": "Traffic by interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "packets/sec",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(rate(arista_port_inUcastPkts{device!~\"Port-Channel.*\", instance=\"$device\"}[1m])*+1) by (device)",
       "legendFormat": "{{device}} IN"
      },
      {
       "expr": "sum(rate(arista_port_outUcastPkts{device!~\"Port-Channel.*\", instance=\"$device\"}[1m])*-1) by (device)",
       "legendFormat": "{{device}} OUT"
      }
     ]
    },
    {
     "title": "bits/sec",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(rate(arista_port_inOctets{device!~\"Port-Channel.*\", instance=\"$device\"}[1m])*+8) by (device)",
       "legendFormat": "{{device}} IN"
      },
      {
       "expr": "sum(rate(arista_port_outOctets{device!~\"Port-Channel.*\", instance=\"$device\"}[1m])*8) by (device)",
       "legendFormat": "{{device}} OUT"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory & Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "arista_power_supply_fan_speed_percent{instance=\"$device\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "System memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "arista_mem_total{instance=\"$device\"}",
     "legendFormat": "Total system memory"
    },
    {
     "expr": "arista_mem_total{instance=\"$device\"} - arista_mem_free{instance=\"$device\"}",
     "legendFormat": "Used system memory"
    }
   ]
  },
  {
   "title": "PSU fan temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "arista_power_supply_temperature{instance=\"$device\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Input/Output power levels",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "arista_power_supply_power{measurement=\"outputPower\", instance=\"$device\"}",
     "legendFormat": "PSU {{id}} current wattage"
    }
   ]
  },
  {
   "title": "Output ampere",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "arista_power_supply_power{measurement=\"outputCurrent\", instance=\"$device\"}",
     "legendFormat": "PSU {{id}}"
    }
   ]
  },
  {
   "title": "Imput voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "arista_power_supply_power{measurement=\"inputVoltage\", instance=\"$device\"}",
     "legendFormat": "PSU {{id}}"
    }
   ]
  },
  {
   "title": "Routing general",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "repeat": "interface",
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "IPv4 unicast routes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "arista_tcam_used{feature=\"V4Routes\",table=\"Routing\", instance=\"$device\"}",
     "legendFormat": "Current IPv4 unicast routes"
    },
    {
     "expr": "arista_tcam_total{feature=\"V4Routes\",table=\"Routing\", instance=\"$device\"}",
     "legendFormat": "Max IPv4 unicast routes"
    }
   ]
  },
  {
   "title": "IPv6 unicast routes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "arista_tcam_used{feature=\"V6Routes\",table=\"Routing\", instance=\"$device\"}",
     "legendFormat": "Current IPv6 unicast routes"
    },
    {
     "expr": "arista_tcam_total{feature=\"V6Routes\",table=\"Routing\", instance=\"$device\"}",
     "legendFormat": "Max IPv6 unicast routes"
    }
   ]
  }
 ]
}